import { createReadStream } from 'node:fs'
import { mkdir, rm, stat, writeFile } from 'node:fs/promises'
import { dirname, resolve, sep } from 'node:path'
import type { Readable } from 'node:stream'

import { Inject, Injectable } from '@nestjs/common'

import { ENV, type Env } from '../config/env'
import { PROJECT_ROOT } from '../project-root'

/**
 * Where uploaded files live. LocalDiskStorage is used now; an S3/R2 implementation can replace it
 * by providing another class for this token in UploadsModule.
 */
export abstract class StorageService {
  abstract save(key: string, data: Buffer): Promise<void>
  abstract open(key: string): Promise<Readable | null>
  abstract remove(key: string): Promise<void>
}

@Injectable()
export class LocalDiskStorage extends StorageService {
  private readonly root: string

  constructor(@Inject(ENV) env: Env) {
    super()
    this.root = resolve(PROJECT_ROOT, env.UPLOAD_DIR)
  }

  /** Keys are generated by the server, but resolve them defensively so nothing escapes the root. */
  private pathFor(key: string) {
    const path = resolve(this.root, key)
    if (!path.startsWith(this.root + sep)) throw new Error(`Invalid storage key: ${key}`)
    return path
  }

  async save(key: string, data: Buffer) {
    const path = this.pathFor(key)
    await mkdir(dirname(path), { recursive: true })
    await writeFile(path, data, { flag: 'wx' })
  }

  async open(key: string) {
    const path = this.pathFor(key)
    try {
      await stat(path)
    } catch {
      return null
    }
    return createReadStream(path)
  }

  async remove(key: string) {
    await rm(this.pathFor(key), { force: true })
  }
}
